title: <p align="center"> Rashmika Reddy </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/RashmikaResume_DS.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rashmika-reddy-8150b4123/">LinkedIn</a> |
  <a href="https://github.com/RashmikaReddy">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing Data Science Masters degree at University of Washington, Seattle.  
  <br><br>
  </p>
  <p align="justify">
  Over 3 years at Microsoft and Amazon, crafting end-to-end data solutions and architecting robust backend systems.
  </p>
  <p align="justify">
  Open for Full-time/New Grad opportunities from March 2024 in Software Engineering, Data Engineering, or Data Science.
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
